dnaStrand1 = "CCGCGTTTTGGCATTGCGCGGAGATTGCACCTAAGCGCGACAGTGCGAGAAATGACCCAAGTACATGCTTAGGACTTAACACAACTTGATTATGTAGCTTAAACCTCTGAGAACCTATTGTGATCGCACCACCGTTTTTCACCTGGTAGCTACAAAGACCGGGTGGATTATGCCAAGCCAGTCGTCAGACTTAGGCGAAGTCCTAGTGATAAGACCCTAGAAACCGAAAAGGAACTCGGTCTTGCTTTCCCCCCGGTAGAGCCGATCACACACTCGCGTTGGGCTTTCGGAAGAACCTTAGGGACGTCGGATGGCTCTGTAAGCCCGGACGGCGAATATGGTGAGGGGGGGGGGGACAGGCGCACCGGTCCCAAGCCTAATACTCCAATCCAAGGTGTTCTTCAACTCACGCACACACTGCCATGAATAACGTAGCTGAACGATAGAGGAAGGGCGCTCTGAAGGCATATGACGTTCATAATTCGGAGTTATGAGCTACTCCTCTTCGAGTGACATGTATAACGACTCTACATTATCAGTCACTGCCACCAGCAGGACCAATGACCAAACGTTCCTAGGGTCTGAGTCGTTAGGTACTAACCATTAGCATCTGCAGAAGCCATCCTACTTCTCCGACGTGCAGTTGGTTATTAGGAGTACTCGATAATTAAATGCGAACATTGAGCGAGTAGACTACGTCGTCTAAGCGAACTGTGTAGAGTCTTCGTGTTAGTCGCGATCGTGGTGTGCCGTGGGTACGCAAGGACGCCCGAGCAACTTTTACACTCGCAGCTGTCCGAAGGCACACCCCAATTAGCTCAGCTATGGGCGCTCCCTGCATTGGAGTGAACGCTATCGGTGCCTTCTCCATAGCCCCAATCAGGCTGGACTGCAACACAATAGACTCGATCGCTACCACGAGTGCGAGGAAGCCGTG"
dnaComplementStrand = list()
for i in range(len(dnaStrand1)):
    if dnaStrand1[i] == 'G':
        dnaComplementStrand.append('C')
        continue
    if dnaStrand1[i] == 'C':
        dnaComplementStrand.append('G')
        continue
    if dnaStrand1[i] == 'A':
        dnaComplementStrand.append('T')
        continue
    if dnaStrand1[i] == 'T':
        dnaComplementStrand.append('A')
        continue
dnaComplementStrand.reverse()
print(''.join(dnaComplementStrand))